# Site settings
site_name: VBA
site_url: https://nodesautomations.com/VBA/

# Repository Details for "Edit on GitHub" links
repo_name: VBA
repo_url: https://github.com/NodesAutomations/VBA
edit_uri: edit/main/docs/

# Navigation Tree
nav:
  - Home:
    - index.md
    - Ribbon.md
    - Speed Up Code.md
    - crack the password on an Excel VBA Project.md
    - Ideas to lock Excel file.md
    - Make VBA Project Unviewable.md
    - Password Breaker Code.md
    - Protect VBA code in Excel.md
    - Remove Password.md
    - Tools.md
    - Unlock VBA password.md
  - Code:
    - Code/AccessModifiers.md
    - Code/Array.md
    - Code/Class.md
    - Code/Collections.md
    - Code/Colors.md
    - Code/ConditinalStatements.md
    - Code/Debugging.md
    - Code/Dictionary.md
    - Code/Enum.md
    - Code/Environment variables.md
    - Code/ErrorHandling.md
    - Code/FileSystem.md
    - Code/Loops.md
    - Code/Math.md
    - Code/MessageBox.md
    - Code/Resources.md
    - Code/Sound.md
    - Code/String.md
    - Code/Switch between Early and Late binding.md
    - Code/TextFile.md
    - Code/Time.md
    - Code/VBA Password.md
    - Code/WindowsAPI.md
    - Code/XML.md
    - Code/ZipFiles.md
  - Excel:
    - Excel/AdvanceFilter.md
    - Excel/Application.md
    - Excel/Assign shortcut key.md
    - Excel/Automatically install addin.md
    - Excel/DocumentProperties.md
    - Excel/Events.md
    - Excel/FileExplorer.md
    - Excel/Formulas.md
    - Excel/Image.md
    - Excel/Images.md
    - Excel/Points.md
    - Excel/Range.md
    - Excel/Resources.md
    - Excel/Sheet.md
    - Excel/SpeedUp.md
    - Excel/Table.md
    - Excel/UserDefineFunctions.md
  - Outlook:
    - Outlook/Create button for macro.md
  - PowerPoint:
    - PowerPoint/Addin.md
    - PowerPoint/Application.md
    - PowerPoint/colors.md
    - PowerPoint/Images.md
    - PowerPoint/References.md
    - PowerPoint/Section.md
    - PowerPoint/Selection.md
    - PowerPoint/Shape.md
    - PowerPoint/Shapes.md
    - PowerPoint/Slide.md
    - PowerPoint/Table.md
  - Word:
    - Word/Bookmark.md
    - Word/Find and Replace.md
    - Word/FindReplace.md
    - Word/Resources.md
    - Word/Sections.md
    - Word/Table.md
  - AutoCAD:
    - AutoCAD/Blocks.md
    - AutoCAD/Blocks_Dynamic.md
    - AutoCAD/Commands.md
    - AutoCAD/Create CUI for DVB.md
    - AutoCAD/Custom Palettes.md
    - AutoCAD/Embedded and Global VBA Projects.md
    - AutoCAD/Entity.md
    - AutoCAD/Hatch.md
    - AutoCAD/Load Autolisp File.md
    - AutoCAD/Resources.md
    - AutoCAD/Selection.md
    - AutoCAD/Startup.md
    - AutoCAD/Symbols.md
    - AutoCAD/XData.md

# Theme
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  version: true
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
    - scheme: default
      primary: black
      accent: indigo
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
  features:
    - content.action.edit # Allows "Edit on GitHub" links
    - content.action.view # Allows "View on GitHub" links
    - content.code.copy # Allows code blocks to have a copy button
    - navigation.path # Enables path navigation top of docs for smaller screens
    - navigation.tabs # Enables tabbed navigation
    - navigation.indexes # Enables attachment of sub section index 
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil 
    view: material/eye

# Extensions
markdown_extensions:
  - admonition # for Callout boxes
  - pymdownx.highlight: 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex: # for rendering math equations
      generic: true
  - def_list # List extensions
  - pymdownx.tasklist: # List extensions
      custom_checkbox: true

# Copyright
copyright: Copyright &copy; 2025 Nodes Automations

# Footer social links
extra:
  generator: false # remove "Generated with MkDocs" footer
  social:
    - icon: fontawesome/solid/globe
      link: https://nodesautomations.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/NodesAutomations
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vivekpatel-nodesautomations/
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/NodesAutomations


